drop table if exists "user" cascade;
drop table if exists apparatuses cascade;
drop table if exists apparatuses_types cascade;
drop table if exists apparatuses_modes cascade;
drop table if exists mods cascade;
drop table if exists apparatuses_operations cascade;
drop table if exists apparatuses_tasks cascade;
drop table if exists operations_apparatuses_products cascade;
drop table if exists operations_modes cascade;
drop table if exists posts cascade;
drop table if exists products cascade;
drop table if exists products_orders cascade;
drop table if exists products_snapshots cascade;
drop table if exists products_tasks cascade;
drop table if exists products_types cascade;
drop table if exists storage_snapshot cascade;
drop table if exists tasks cascade;
drop table if exists technical_tasks cascade;
drop table if exists products_derivatives cascade;
drop type if exists apparatus_type;
drop type if exists profession;
drop type if exists product_type;
drop function if exists truncate_if_exists(_table text, _schema text);
drop function if exists create_snapshot_storage();